'use client';
import { useState } from 'react';
import { Search, RefreshCw, Users, Clock3 } from 'lucide-react';
import { api } from '@/lib/api';
import { Avatar, Empty, LoadState, PageHeader, Metric, dateLabel, useRemote } from '@/components/workspace';
export default function TeamPage() {
 const remote = useRemote<any[]>(() => api.currentWork.getWhoIsDoingWhat());
 const [search, setSearch] = useState('');
 const members = (remote.data || []).filter(m => m.fullName.toLowerCase().includes(search.toLowerCase()));
 return <><PageHeader eyebrow="WORKSPACE / CON NGƯỜI" title="Đội nhóm" subtitle="Nắm bắt tình hình nhân sự và khối lượng công việc."><button className="btn" onClick={remote.reload} disabled={remote.loading}><RefreshCw size={15} />Làm mới</button></PageHeader><LoadState loading={remote.loading} error={remote.error} retry={remote.reload} />{remote.data && <><div className="metrics"><Metric label="Thành viên" value={remote.data.length} icon={<Users size={17} />} /><Metric label="Đang trong ca" value={remote.data.filter(m => m.isCheckedIn).length} tone="positive" /><Metric label="Đang cập nhật công việc" value={remote.data.filter(m => m.currentWork?.statusText).length} icon={<Clock3 size={17} />} /><Metric label="Có công việc quá hạn" value={remote.data.filter(m => m.overdueTasksCount > 0).length} tone="danger" /></div><div className="toolbar"><label className="search-field"><Search size={16} /><input aria-label="Tìm thành viên" placeholder="Tìm thành viên..." value={search} onChange={e => setSearch(e.target.value)} /></label></div><div className="team-grid">{members.map((m,i) => <article className="member-card" key={m.userId}><div className="member-head"><Avatar name={m.fullName} size="large" index={i} /><div><h3>{m.fullName}</h3><p className="muted">{m.email}</p></div></div><span className={'status ' + (m.isCheckedIn ? 'status-active' : 'status-paused')}><span className="status-dot" />{m.isCheckedIn ? 'Đang trong ca' : 'Ngoài ca'}</span><div className="member-work"><div className="eyebrow">CÔNG VIỆC HIỆN TẠI</div><p>{m.currentWork?.statusText || 'Chưa cập nhật'}</p></div><div className="member-footer"><span><strong>{m.remainingTasksCount}</strong> việc còn lại</span><span className={m.overdueTasksCount ? 'overdue' : 'muted'}>{m.overdueTasksCount} quá hạn</span></div><div className="mini-stat"><span>Hạn gần nhất</span><span>{dateLabel(m.nearestDeadline)}</span></div></article>)}</div>{!members.length && <Empty title="Không tìm thấy thành viên" />}</>}</>;
}
