'use client';
import Link from 'next/link';
import { useState } from 'react';
import { api } from '@/lib/api';
import { ArrowRight, CalendarDays, CheckCheck, Clock3, Flag, Plus, Sparkles, TrendingUp } from 'lucide-react';
import { Avatar, CompletionButton, dateLabel, Empty, LoadState, Metric, PageHeader, Status, useRemote, useWorkspace } from '@/components/workspace';
export default function TodayPage(){
  const {user,notify}=useWorkspace();
  const tasks=useRemote(()=>api.tasks.getToday());
  const team=useRemote(()=>api.currentWork.getWhoIsDoingWhat());
  const work=useRemote(()=>api.currentWork.getMe());
  const [text,setText]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('all');
  const data=tasks.data;
  const unique=Array.from(new Map([...(data?.doing||[]),...(data?.overdue||[]),...(data?.dueToday||[]),...(data?.upcoming||[]),...(data?.noDeadline||[])].map((t:any)=>[t.id,t])).values()) as any[];
  const visible=tab==='overdue'?data?.overdue||[]:tab==='completed'?data?.completedToday||[]:unique;
  const complete=async(t:any)=>{setBusy(true);try{await api.tasks.update(t.id,{status:t.status==='COMPLETED'?'TODO':'COMPLETED'});await tasks.reload();notify('Đã cập nhật công việc');}catch(e:any){notify(e.message,true);}finally{setBusy(false);}};
  return <>
    <PageHeader eyebrow={new Date().toLocaleDateString('vi-VN',{weekday:'long',day:'numeric',month:'long',year:'numeric'})} title={'Chào '+(user?.fullName?.split(' ').slice(-1)[0]||'bạn')+', ngày mới tốt lành.'} subtitle="Mọi việc quan trọng, trong một góc nhìn."><Link className="btn" href="/reports"><TrendingUp size={14}/>Xem báo cáo</Link><Link className="btn btn-primary" href="/tasks?new=1"><Plus size={15}/>Tạo công việc</Link></PageHeader>
    <LoadState error={tasks.error} retry={tasks.reload}/>{tasks.loading&&!data?<LoadState loading/>:data&&<>
    <div className="metrics"><Metric label="Công việc đang mở" value={unique.length} detail="Được phân công cho bạn" icon={<Flag/>}/><Metric label="Đến hạn hôm nay" value={data.dueToday.length} detail="Cần ưu tiên trong ngày" icon={<CalendarDays/>}/><Metric label="Đã hoàn thành" value={data.completedToday.length} detail="Tính trong ngày hôm nay" icon={<CheckCheck/>} tone="positive"/><Metric label="Đang trễ hạn" value={data.overdue.length} detail="Cần được xử lý sớm" icon={<Clock3/>} tone="danger"/></div>
    <div className="dashboard-grid"><div>
      <section className="section"><div className="section-heading"><div><h2>Công việc của tôi <span className="count">{unique.length}</span></h2><p>Ưu tiên đúng việc. Giữ nhịp tiến độ.</p></div><Link href="/tasks" className="link-action">Tất cả công việc<ArrowRight size={13}/></Link></div>
      <div className="tabs" role="tablist">{[['all','Đang mở'],['overdue','Trễ hạn'],['completed','Hoàn thành hôm nay']].map(([id,label])=><button role="tab" aria-selected={tab===id} key={id} className={'tab'+(tab===id?' active':'')} onClick={()=>setTab(id)}>{label}</button>)}</div>
      {visible.length?<div className="table-wrap"><table><thead><tr><th>Công việc</th><th>Trạng thái</th><th>Hạn hoàn thành</th></tr></thead><tbody>{visible.slice(0,8).map((t:any)=><tr key={t.id}><td className="task-title-cell"><div className="task-title"><CompletionButton completed={t.status==='COMPLETED'} disabled={busy} onClick={()=>complete(t)}/><div><Link className="strong" href={'/tasks?task='+t.id}>{t.title}</Link><small>{t.project?.name||t.team?.name||'Công việc cá nhân'}</small></div></div></td><td><Status value={t.status}/></td><td className={t.isOverdue?'overdue':'muted'}>{dateLabel(t.deadline)}</td></tr>)}</tbody></table></div>:<div className="panel"><Empty title="Bạn đã bắt kịp mọi việc" detail="Công việc được giao sẽ xuất hiện tại đây."><Link href="/tasks?new=1" className="btn btn-small"><Plus size={13}/>Thêm công việc</Link></Empty></div>}</section>
      <section className="section"><div className="section-heading"><h2>Nhịp làm việc đội nhóm</h2><Link className="link-action" href="/team">Xem đội nhóm<ArrowRight size={13}/></Link></div><div className="table-wrap"><table><thead><tr><th>Thành viên</th><th>Đang thực hiện</th><th>Ca làm việc</th></tr></thead><tbody>{(team.data||[]).slice(0,5).map((m:any,i:number)=><tr key={m.userId}><td><div className="person"><Avatar name={m.fullName} index={i}/>{m.fullName}</div></td><td className="task-title-cell muted">{m.currentWork?.statusText||'Chưa cập nhật'}</td><td><Status value={m.isCheckedIn?'OPEN':'CLOSED'}/></td></tr>)}</tbody></table>{!team.data?.length&&<Empty title="Chưa có hoạt động đội nhóm"/>}</div></section>
    </div><aside className="dashboard-aside">
      <section className="side-section"><div className="section-heading"><h2><Sparkles size={16} color="var(--green)"/>Work AI</h2><span className="count">Trợ lý</span></div><div className="ai-note"><strong>Tâm điểm hôm nay</strong>{data.overdue.length?data.overdue.length+' công việc đang trễ hạn. Hãy kiểm tra các đầu việc cần hỗ trợ.':data.dueToday.length?data.dueToday.length+' công việc đến hạn hôm nay.':'Chưa có công việc đến hạn hôm nay.'}</div><Link href="/assistant?q=Thống kê công việc hôm nay" className="link-action">Cùng AI xem tiến độ<ArrowRight size={13}/></Link></section>
      <section className="side-section"><div className="section-heading"><h2>Bạn đang làm gì?</h2></div><p className="muted small" style={{marginBottom:13}}>{work.data?.customStatusText||'Chưa cập nhật trạng thái'}</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api.currentWork.setMe({customStatusText:text});setText('');await work.reload();notify('Đã cập nhật trạng thái');}catch(e:any){notify(e.message,true);}finally{setBusy(false);}}}><label className="field"><input aria-label="Trạng thái làm việc" placeholder="Cập nhật công việc hiện tại..." value={text} onChange={e=>setText(e.target.value)} maxLength={250}/></label><button className="btn btn-small" disabled={busy||!text.trim()}>Cập nhật trạng thái<ArrowRight size={12}/></button></form></section>
      <section><div className="section-heading"><h2>Tiến độ hôm nay</h2></div><div className="mini-stat"><span>Hoàn thành</span><strong>{data.completedToday.length}/{unique.length+data.completedToday.length}</strong></div><div className="progress-track"><div className="progress-fill" style={{width:(data.completedToday.length/Math.max(1,unique.length+data.completedToday.length)*100)+'%'}}/></div><div className="mini-stat"><span>Đang thực hiện</span><strong>{data.doing.length}</strong></div><div className="mini-stat"><span>Sắp đến hạn</span><strong>{data.upcoming.length}</strong></div></section>
    </aside></div></>}
  </>;
}
