'use client';
import { useState } from 'react';
import { Download, BarChart3 } from 'lucide-react';
import { api, apiUrl } from '@/lib/api';
import { PageHeader, Metric, LoadState, useRemote, useWorkspace } from '@/components/workspace';
export default function ReportsPage() {
 const remote = useRemote(() => api.reports.getSummary());
 const { notify } = useWorkspace();
 const [busy, setBusy] = useState(false);
 async function download(kind: string) {
  setBusy(true); try { const token = localStorage.getItem('work_session_token'); const response = await fetch(apiUrl('/reports/export/' + kind), { credentials: 'include', headers: token ? { Authorization: 'Bearer ' + token } : {} }); if (!response.ok) throw new Error('Không thể xuất báo cáo'); const url = URL.createObjectURL(await response.blob()); const a = document.createElement('a'); a.href = url; a.download = kind + '.csv'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); } catch (e: any) { notify(e.message, true); } finally { setBusy(false); }
 }
 const s = remote.data;
 return <><PageHeader eyebrow="WORKSPACE / HIỆU SUẤT" title="Báo cáo" subtitle="Số liệu trong phạm vi công việc bạn được phép xem."><button className="btn" disabled={busy} onClick={() => download('attendance')}><Download size={15} />Chấm công CSV</button><button className="btn btn-primary" disabled={busy} onClick={() => download('tasks')}><Download size={15} />Công việc CSV</button></PageHeader><LoadState loading={remote.loading} error={remote.error} retry={remote.reload} />{s && <><div className="metrics"><Metric label="Tổng công việc" value={s.totalTasks} icon={<BarChart3 size={17} />} /><Metric label="Đang thực hiện" value={s.inProgressTasks} /><Metric label="Hoàn thành" value={s.completedTasks} tone="positive" /><Metric label="Quá hạn" value={s.overdueTasks} tone="danger" /></div><div className="dashboard-grid"><section className="section"><div className="section-heading"><h2>Phân bổ công việc</h2><span className="muted">Hiện tại</span></div>{[{label:'Đã hoàn thành', value:s.completedTasks, color:'#157a66'}, {label:'Đang thực hiện', value:s.inProgressTasks, color:'#537eb4'}, {label:'Các trạng thái khác', value:s.totalTasks-s.completedTasks-s.inProgressTasks,color:'#9a83ad'}].map(item => <div key={item.label} style={{margin:'28px 0'}}><div className="mini-stat"><span>{item.label}</span><strong>{item.value}</strong></div><div className="progress-track" style={{height:12}}><div className="progress-fill" style={{width:(s.totalTasks ? item.value / s.totalTasks * 100 : 0)+'%',background:item.color}} /></div></div>)}</section><aside><section className="side-section"><h3>Chất lượng bàn giao</h3><div className="metric-value positive">{s.onTimeDeliveryRate}</div><p className="muted">Tỷ lệ hoàn thành đúng hạn</p><div className="mini-stat"><span>Việc cần chú ý</span><strong className="overdue">{s.overdueTasks}</strong></div></section></aside></div><section className="section"><div className="section-heading"><h2>Công việc theo nhóm chat</h2></div><div className="table-wrap"><table><thead><tr><th>Nhóm chat</th><th>Tổng</th><th>Đang làm</th><th>Hoàn thành</th><th>Quá hạn</th></tr></thead><tbody>{s.byConversation?.map((room: any) => <tr key={room.id}><td><a href={`/chat?conversation=${encodeURIComponent(room.id)}`}>{room.name}</a></td><td>{room.total}</td><td>{room.inProgress}</td><td>{room.completed}</td><td className="overdue">{room.overdue}</td></tr>)}</tbody></table></div></section></>}</>;
}
